<?php
function awards_header_options( $options = array() ){
	$options = array(
	  array(
        'id'          => 'header_slide_menu',
        'label'       => esc_html__( 'Display Slide Header Menu', 'awards' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	array(
        'id'          => 'search_icon_in_menu',
        'label'       => esc_html__( 'Display Search Icon in Header Menu', 'awards' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'login_button_in_menu',
        'label'       => esc_html__( 'Display Submit Site Button in Header', 'awards' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'header_login_page',
        'label'       => esc_html__( 'Login Page', 'awards' ),
        'desc'        => esc_html__( 'create a page and insert login shortcode and set it as login page.', 'awards' ),
        'std'         => '',
        'type'        => 'page-select',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'login_button_in_menu:not(off)',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'header_submit_site_page',
        'label'       => esc_html__( 'Submit Site Page Link', 'awards' ),
        'desc'        => esc_html__( 'create a page and set page template "Submit Site Template" and set it submit site page', 'awards' ),
        'std'         => '',
        'type'        => 'page-select',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'login_button_in_menu:not(off)',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'paid_submit_site_page',
        'label'       => esc_html__( 'Payment Page', 'awards' ),
        'desc'        => esc_html__( 'create a page and set page template "Payment Template" and set it payment site page', 'awards' ),
        'std'         => '',
        'type'        => 'page-select',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'login_button_in_menu:not(off)',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'thank_you_page',
        'label'       => esc_html__( 'Thank You Page', 'awards' ),
        'desc'        => esc_html__( 'create a page and add your thank you content, it will redirect after successfully submit site.', 'awards' ),
        'std'         => '',
        'type'        => 'page-select',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'show_breadcrumbs',
        'label'       => esc_html__( 'Display Breadcrumbs', 'awards' ),
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
	  array(
        'id'          => 'bredcrumb_menu_prefix',
        'label'       => esc_html__( 'Breadcrumb Prefix', 'awards' ),
        'desc'        => esc_html__( 'Breadcrumb prefix', 'awards' ),
        'std'         => 'Home',
        'type'        => 'text',
        'section'     => 'header_options',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => 'show_breadcrumbs:not(off)',
        'operator'    => 'and'
      ),
	);
	return apply_filters( 'awards_header_options', $options );
} 
?>